#generate docker image used for development with VS-code see: https://code.visualstudio.com/docs/remote/containers
FROM ghcr.io/fmahiant/modbus-gateway-sdk:latest
RUN  apt-get -y update && apt-get -qq -y install git